// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BenchmarkQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['BenchmarkQuery'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearExecutionHistory() {
  return window['go']['main']['App']['ClearExecutionHistory']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateConnectionProfile(arg1) {
  return window['go']['main']['App']['CreateConnectionProfile'](arg1);
}

export function CreateQuery(arg1) {
  return window['go']['main']['App']['CreateQuery'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteConnectionProfile(arg1) {
  return window['go']['main']['App']['DeleteConnectionProfile'](arg1);
}

export function DeleteQuery(arg1) {
  return window['go']['main']['App']['DeleteQuery'](arg1);
}

export function DuplicateQuery(arg1) {
  return window['go']['main']['App']['DuplicateQuery'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExplainQuery(arg1, arg2) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2);
}

export function ExportDataJSON() {
  return window['go']['main']['App']['ExportDataJSON']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetQuery(arg1) {
  return window['go']['main']['App']['GetQuery'](arg1);
}

export function GetQueryVersions(arg1) {
  return window['go']['main']['App']['GetQueryVersions'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportDataJSON(arg1) {
  return window['go']['main']['App']['ImportDataJSON'](arg1);
}

export function ImportQueriesFromFolder(arg1) {
  return window['go']['main']['App']['ImportQueriesFromFolder'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IntrospectSchema(arg1) {
  return window['go']['main']['App']['IntrospectSchema'](arg1);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListConnectionProfiles() {
  return window['go']['main']['App']['ListConnectionProfiles']();
}

export function ListExecutionHistory(arg1) {
  return window['go']['main']['App']['ListExecutionHistory'](arg1);
}

export function ListQueries(arg1) {
  return window['go']['main']['App']['ListQueries'](arg1);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenReleasePage() {
  return window['go']['main']['App']['OpenReleasePage']();
}

export function ResetData() {
  return window['go']['main']['App']['ResetData']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SelectFolderDialog() {
  return window['go']['main']['App']['SelectFolderDialog']();
}

export function SyncQueriesToFolder(arg1) {
  return window['go']['main']['App']['SyncQueriesToFolder'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TouchQuery(arg1) {
  return window['go']['main']['App']['TouchQuery'](arg1);
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateConnectionProfile(arg1) {
  return window['go']['main']['App']['UpdateConnectionProfile'](arg1);
}

export function UpdateQuery(arg1) {
  return window['go']['main']['App']['UpdateQuery'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
