// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {updater} from '../models';

export function BenchmarkQuery(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.BenchmarkResult>;

export function CheckForUpdate():Promise<updater.Info>;

export function ClearExecutionHistory():Promise<void>;

export function CreateCollection(arg1:models.Collection):Promise<models.Collection>;

export function CreateConnectionProfile(arg1:models.ConnectionProfile):Promise<models.ConnectionProfile>;

export function CreateQuery(arg1:models.Query):Promise<models.Query>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteConnectionProfile(arg1:string):Promise<void>;

export function DeleteQuery(arg1:string):Promise<void>;

export function DuplicateQuery(arg1:string):Promise<models.Query>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.QueryResult>;

export function ExplainQuery(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportDataJSON():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetQuery(arg1:string):Promise<models.Query>;

export function GetQueryVersions(arg1:string):Promise<Array<models.QueryVersion>>;

export function GetSettings():Promise<models.Settings>;

export function ImportDataJSON(arg1:string):Promise<void>;

export function ImportQueriesFromFolder(arg1:string):Promise<number>;

export function InstallUpdate():Promise<updater.Result>;

export function IntrospectDatabase(arg1:string,arg2:string):Promise<Array<models.TableInfo>>;

export function IntrospectSchema(arg1:string):Promise<Array<models.TableInfo>>;

export function ListCollections():Promise<Array<models.Collection>>;

export function ListConnectionProfiles():Promise<Array<models.ConnectionProfile>>;

export function ListDatabases(arg1:string):Promise<Array<string>>;

export function ListExecutionHistory(arg1:number):Promise<Array<models.ExecutionLog>>;

export function ListQueries(arg1:models.SearchFilter):Promise<Array<models.Query>>;

export function ListTags():Promise<Array<models.Tag>>;

export function OpenFileDialog():Promise<string>;

export function OpenReleasePage():Promise<void>;

export function ResetData():Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectFolderDialog():Promise<string>;

export function SyncQueriesToFolder(arg1:string):Promise<number>;

export function TestConnection(arg1:models.ConnectionProfile):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<boolean>;

export function TouchQuery(arg1:string):Promise<void>;

export function UpdateCollection(arg1:models.Collection):Promise<void>;

export function UpdateConnectionProfile(arg1:models.ConnectionProfile):Promise<void>;

export function UpdateQuery(arg1:models.Query):Promise<models.Query>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
